### ISSUE TITLE
Issue with use of color in reporter

### ISSUE THREAD

**Issue by drradwan** [juhovh/mocha-jenkins-reporter#19]
When using this reporter with Jenkins, the forced use of color doesn't work right for me.  Not only does Jenkins not support color on the console output, it ends up injecting ANSI symbols into my XML file on failure and the XML parser ends up dying when trying to load test results.  Can you please fix this in the mainline?

Thanks,
--Adam

**Comment by juhovh** [comment]
The instructions on the readme say: Make sure to set the Color ANSI Console Output on and use for example xterm for the ANSI color map setting, in order to show the output colors nicely in Jenkins.

Does changing this setting change anything for you? It should never inject ANSI symbols into your XML file, could you please provide a sample test case to let me look into this?

**Comment by drradwan** [comment]
Thanks for getting back with me on this.  I guess the instructions weren't
so clear on browing the plugins for one called "AnsiColor" and enabling it
for this project with 'xterm' set.  Once I figured this out, it is showing
me color on the console output, however it is still failing at the XML
parser unless I use a Regular Expression search and replace string to fix
it.  Here's what I see when mocha fails and the JUnit XML file gets read in
(when trying to click on "Test Result" for a build):

Also, here's the RegExp line to fix the error: sed -i 's/'$(echo -e
"\033.*m")'//g' reports/$(ls -1r reports | head -1)

Stacktrace

Failed to read test report file
/var/lib/jenkins/jobs/iPortal/workspace/reports/1428000353434.xml
org.dom4j.DocumentException: Error on line 28 of document
file:///var/lib/jenkins/jobs/iPortal/workspace/reports/1428000353434.xml
: An invalid XML character (Unicode: 0x{2}) was found in the value of
attribute "{1}" and element is "1b". Nested exception: An invalid XML
character (Unicode: 0x{2}) was found in the value of attribute "{1}"
and element is "1b".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:123)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:282)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:228)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:163)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:146)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:122)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:119)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:92)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:89)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:121)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:138)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: org.xml.sax.SAXParseException; systemId:


Thanks,

--Adam

**Comment by juhovh** [comment]
Could you send me the broken report xml somewhere so I could try to figure out why it's breaking?
