### ISSUE TITLE
Issue with building using 0.1.7

### ISSUE THREAD

**Issue by abullrd** [juhovh/mocha-jenkins-reporter#21]
Hello,

After the update to `0.1.7` this morning we started seeing these failures w/ our build system. I've pinned to `0.1.6` for now. Just thought you'd like to know, thanks for the great work and let me know if I can help identify the issue!

```
[4mRunning "mochaTest:integration" (mochaTest) task[24m
[31m>> [39mMocha exploded!
[31m>> [39mTypeError: Cannot read property 'reporterOptions' of undefined[31m
>> [39m    at new Jenkins (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/mocha-jenkins-reporter/lib/jenkins.js:38:24)[31m
>> [39m    at MochaWrapper.run (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:52:27)[31m
>> [39m    at /var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt-mocha-test/tasks/mocha.js:72:20[31m
>> [39m    at capture (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt-mocha-test/tasks/mocha.js:27:5)[31m
>> [39m    at Object.<anonymous> (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt-mocha-test/tasks/mocha.js:67:5)[31m
>> [39m    at Object.<anonymous> (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/grunt/task.js:264:15)[31m
>> [39m    at Object.thisTask.fn (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/grunt/task.js:82:16)[31m
>> [39m    at Object.<anonymous> (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/util/task.js:301:30)[31m
>> [39m    at Task.runTaskFn (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/util/task.js:251:24)[31m
>> [39m    at Task.<anonymous> (/var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/util/task.js:300:12)[31m
>> [39m    at /var/lib/jenkins/jobs/server-ci/workspace/node_modules/grunt/lib/util/task.js:227:11[31m
>> [39m    at process._tickDomainCallback (node.js:463:13)
[33mWarning: Task "mochaTest:integration" failed. Use --force to continue.[39m

[31mAborted due to warnings.[39m
Build step 'Execute shell' marked build as failure
Archiving artifacts
```

**Comment by juhovh** [comment]
This would seem to be a regression when an old version of mocha (or in this case grunt-mocha-test) is used. I just published 0.1.8 which should fix this issue, please test it if you can.

**Comment by abullrd** [comment]
I will do that soon, thanks for the quick response!

**Comment by abullrd** [comment]
Looks like that did the trick! Thanks again.

**Comment by jvah** [comment]
No problem, thanks for reporting! Probably wouldn't have noticed myself.

**Comment by abullrd** [comment]
Yeah, we really need to get on w/ updating our test suite at some point...
