### ISSUE TITLE
bad error for invalid JUNIT_REPORT_PATH

### ISSUE THREAD

**Issue by Akuukis** [juhovh/mocha-jenkins-reporter#42]
If you use path that jenkins do not have permissions to write to, for example
```
JUNIT_REPORT_PATH=/results.xml
```
then it errors like this:
```
$ node_modules/.bin/mocha test --reporter mocha-jenkins-reporter
TypeError: Cannot read property 'failures' of undefined
    at Runner.<anonymous> (/<mypath>/node_modules/mocha-jenkins-reporter/lib/jenkins.js:332:27)
    at emitTwo (events.js:105:20)
    at Runner.emit (events.js:185:7)
    at Runner.fail (/<mypath>/node_modules/mocha/lib/runner.js:233:8)
    at Runner.uncaught (/<mypath>/node_modules/mocha/lib/runner.js:683:12)
    at process.uncaught (/<mypath>/node_modules/mocha/lib/runner.js:783:10)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:236:26)
```
and if I do `npm install options` for curiousness, then it errors
```
$ npm install options
$ node_modules/.bin/mocha test --reporter mocha-jenkins-reporter
<mypath>/node_modules/mocha-jenkins-reporter/lib/jenkins.js:332
    var n = ++currentSuite.failures;
                          ^

TypeError: Cannot read property 'failures' of undefined
    at Runner.<anonymous> (/<mypath>/node_modules/mocha-jenkins-reporter/lib/jenkins.js:332:27)
    at emitTwo (events.js:105:20)
    at Runner.emit (events.js:185:7)
    at Runner.fail (/<mypath>/node_modules/mocha/lib/runner.js:233:8)
    at Runner.uncaught (/<mypath>/node_modules/mocha/lib/runner.js:683:12)
    at process.uncaught (/<mypath>/node_modules/mocha/lib/runner.js:783:10)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:236:26)
```

Imo these errors are misleading and module should return useful error.

**Comment by jvah** [comment]
You are right and I can reproduce the issue, I'll look into this.
