### ISSUE TITLE
Running mocha with --use-strict argument generates "Octal literals are not allowed in strict mode"

### ISSUE THREAD

**Issue by rmemoria** [juhovh/mocha-jenkins-reporter#44]
I'm using mocha 2.5.3.

I'm writing test cases using some ES6 features (like classes and promises), and it requires me to run them with the --use-strict command line argument in nodejs.

When doing that, I get the error message when selecting 'mocha-jenkins-reporter' as the output:

`SyntaxError: Octal literals are not allowed in strict mode.`

This is the full trace log:

```
yntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/rmemoria/Projects/etbmanager/etbm3/node_modules/mocha-jenkins-reporter/lib/jenkins.js:11:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/rmemoria/Projects/etbmanager/etbm3/node_modules/mocha-jenkins-reporter/index.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Mocha.reporter (/usr/local/lib/node_modules/mocha/lib/mocha.js:151:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:208:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
/usr/local/lib/node_modules/mocha/lib/mocha.js:164
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "mocha-jenkins-reporter"
    at Mocha.reporter (/usr/local/lib/node_modules/mocha/lib/mocha.js:164:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:208:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

**Comment by juhovh** [comment]
Should be fixed in 0.2.3.
