### ISSUE TITLE
Failure in before() shows unnecessary exception

### ISSUE THREAD

**Issue by pendix** [juhovh/mocha-jenkins-reporter#51]
If before() fails, the jenkins reporter shows unnecessary "TypeError: Path must be a string. Received undefined" exception as test.file is not defined.

Test case:

```
describe('mytest', function() {
    before(function() { return Promise.reject("fail"); });
    it('never reached', function(done) { done(); });
});
```

Result:

```
  mytest
      1) "before all" hook

  Suite duration: 0.006 s, Tests: 1
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1229:5)
    at getRelativePath (/home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:259:17)
    at getClassName (/home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:270:25)
    at /home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:117:45
    at Array.forEach (native)
    at genSuiteReport (/home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:115:11)
    at endSuite (/home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:187:7)
    at Runner.<anonymous> (/home/test/project/node_modules/mocha-jenkins-reporter/lib/jenkins.js:298:5)
    at emitNone (events.js:91:20)
    at Runner.emit (events.js:185:7)
    at /home/test/project/node_modules/mocha/lib/runner.js:786:12
    at /home/test/project/node_modules/mocha/lib/runner.js:639:9
    at next (/home/test/project/node_modules/mocha/lib/runner.js:284:14)
    at Immediate.<anonymous> (/home/test/project/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

  0 passing (9ms)
  1 failing

  1) mytest "before all" hook:
     Error: the string "fail" was thrown, throw an Error :)
      at runMicrotasksCallback (internal/process/next_tick.js:58:5)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

Suggestion: change mocha-jenkins-reporter/lib/jenkins.js getRelativePath() to have e.g:
    return path.relative(absoluteTestDir, test.file);
-->
    return path.relative(absoluteTestDir, test.file || "");

Best would be if the test file would be available at this time, though...

**Comment by jvah** [comment]
The suggested fix added to master.
