### ISSUE TITLE
XML output no longer contains any diff/stacktrace

### ISSUE THREAD

**Issue by mabako** [juhovh/mocha-jenkins-reporter#56]
Hey,

I believe [bc68d34](https://github.com/juhovh/mocha-jenkins-reporter/commit/bc68d34e00532b4028c7956718fdbb509e820128#diff-9f752b0ccde7d56a09ee06c71cd60d76L127) broke the ability to view the test output and stack traces, since the call to `unifiedDiff` was removed (and not re-added since).

Sample test case:

```js
var assert = require('assert');

function n(x) {
  if(x <= 0)
    assert.equal(1, 0, "this message will show up in the XML, but the stack trace will not");

  n(x-1);
}

describe("demo", function () {
  it("works", function (done) {
    n(3);
    done();
  });
});
```

Run with:
```sh
mocha --reporter mocha-jenkins-reporter --reporter-options junit_report_stack=1,junit_report_path=output.xml test/
```

Console output:
```
  bla
      1) works

  Suite duration: 0.006 s, Tests: 1

  0 passing (8ms)
  1 failing

  1) bla works:

      AssertionError: this message will show up in the XML, but the stack trace will not
      + expected - actual

      -1
      +0

      at n (test\demo.js:5:12)
      at n (test\demo.js:7:3)
      at n (test\demo.js:7:3)
      at n (test\demo.js:7:3)
      at Context.<anonymous> (test\demo.js:12:5)
```

XML output
```
<testsuites name="Mocha Tests">
  <testsuite name="demo" tests="1" errors="0" failures="1" skipped="0" timestamp="2016-11-29T12:59:57" time="0.006">
    <testcase classname="demo" name="works" time="0.001">
      <failure message="this message will show up in the XML, but the stack trace will not">
      </failure>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by juhovh** [comment]
I just released 0.3.2 which should fix this issue, please confirm and reopen this issue if that is not the case. Thank you for reporting and sorry for the delay!
