### ISSUE TITLE
Jump from 0.3.1 to 0.3.2 is a major change (no backward compatible)

### ISSUE THREAD

**Issue by endrebock-home24** [juhovh/mocha-jenkins-reporter#57]
See follow message: 
```
"mocha-jenkins-reporter" reporter blew up with error:
…workdir/node_modules/mocha-jenkins-reporter/lib/jenkins.js:356
      startSuite({tests:["other"], fullTitle: () => { return "Non-test failure
                                               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (…workdir/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (…workdir/node_modules/mocha-jenkins-reporter/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (…workdir/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Mocha.reporter (…workdir/node_modules/mocha/lib/mocha.js:153:21)
    at Object.<anonymous> (…workdir/node_modules/mocha/bin/_mocha:213:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (…workdir/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (…workdir/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at …workdir/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at …workdir/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at …workdir/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at …workdir/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at …workdir/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (…workdir/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at …workdir/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at …workdir/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1474:14)
    at process._tickCallback (node.js:355:11)
```
Installing `0.3.1` solves the problem.

Running on:
```
$ nodejs --version
v0.12.9
```

**Comment by jvah** [comment]
This is a result of PR #52 introducing ES6 requirement, which is bad. I didn't notice this because I'm using ES6 supporting Node.js myself. I now added a eslint configuration that should catch these better in the future. Please upgrade to 0.3.3 and let me know if that fixes the issue for you.

**Comment by endrebock-home24** [comment]
Version `0.3.3` works fine on nodejs v0.12.

Thank you :+1:

**Comment by jvah** [comment]
Cool, sorry I missed this and thank you for reporting.
